title: Kyle Thomson # your name (or website title) here
logo: "/images/Kyle_Thomson.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi! I'm Kyle, a data analytics professional with a passion for ethical data-driven storytelling through cross-collaboration 
  <br><br>
  My background includes roles in Healthcare and Product analytics. I love working with open-ended questions and areas of high ambiguity.
  Please, stay a while and learn how I could add value to your team!
  <br><br>
  <a href="https://www.linkedin.com/in/kylethomson2/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
